### ISSUE TITLE
Improve responsiveness

### ISSUE THREAD

**Issue by officialarmannqureshi** [officialarmannqureshi/vlabsolutions#1]
Here is the view of the issue!
<img width="317" alt="image" src="https://github.com/officialarmannqureshi/vlabsolutions/assets/91754196/4dc2c5f0-07bb-46bc-9c6f-e9fb7690dfb8">

**Comment by HuzaifaAhmad03** [comment]
I would like to contribute on this

**Comment by officialarmannqureshi** [comment]
Assigned @HuzaifaAhmad03.Thank you

**Comment by GautamRaj-12** [comment]
Hey, Can I work on this?

**Comment by Rohansaini1512** [comment]
hello @officialarmannqureshi  i would like to contribute in this . please assign this to me

**Comment by officialarmannqureshi** [comment]
@Rohansaini1512 Hey Rohan, I have assigned this issue to you.
