### ISSUE TITLE
Fetch the problem statement from the pending assignments stored in database

### ISSUE THREAD

**Issue by officialarmannqureshi** [officialarmannqureshi/vlabsolutions#16]
<img width="950" alt="275351035-25e2aba5-9c45-441f-9186-9f581cb9d6c0" src="https://github.com/officialarmannqureshi/vlabsolutions/assets/91754196/eb104260-ca3f-4c17-b193-9cffcd7ebe39">

**Comment by Rohansaini1512** [comment]
@officialarmannqureshi please assign this issue to me

**Comment by JAYBORICHA07** [comment]
If this issue is still open would love to contribute to it
@officialarmannqureshi

**Comment by officialarmannqureshi** [comment]
yes you can @JAYBORICHA07
