### ISSUE TITLE
No CONTRIBUTING.md file

### ISSUE THREAD

**Issue by AnikethDeb2004** [officialarmannqureshi/vlabsolutions#19]
**Since there's no  No CONTRIBUTING.md file how can we understand where to contribute and on what !
Hence, its recommended to add the required file asap:)**

**Comment by officialarmannqureshi** [comment]
Thanks for your feedback.I'll add it soon.

**Comment by officialarmannqureshi** [comment]
Resolved by @pinak-dhir
