### ISSUE TITLE
Perfer to use template string(``) on normal string in /config/db.js

### ISSUE THREAD

**Issue by manzil-infinity180** [officialarmannqureshi/vlabsolutions#23]
Current version 
const connectDB = async () => {
    try {
        const conn = await mongoose.connect(process.env.MONGO_DB, { useNewUrlParser: true });
        
        console.log("Server connected to DB successfully ${conn.connection.host}");
    } catch (error) {
        console.log('Error in connecting DB or error :${error}');
        
    }
}
<img width="483" alt="Screenshot 2023-12-11 at 6 41 49 PM" src="https://github.com/officialarmannqureshi/vlabsolutions/assets/119070053/77863a19-8d77-442a-9e2e-9a093e4112ee">

for this lines of code we can perfer to use template string , how the developer can find what the error is if we use normal string 

Expected 
<img width="688" alt="Screenshot 2023-12-11 at 6 42 25 PM" src="https://github.com/officialarmannqureshi/vlabsolutions/assets/119070053/4b46280c-13bc-427e-859c-36313f1c24b4">

**Comment by officialarmannqureshi** [comment]
Resolved by @manzil-infinity180
